### ISSUE TITLE
请问下，puppeteer可以做阿里妈妈的登录模拟吗

### ISSUE THREAD

**Issue by Bangood** [zhentaoo/puppeteer-deep#10]
请问下，puppeteer可以做阿里妈妈的登录模拟吗

**Comment by zhentaoo** [comment]
可以，需要提供账户/密码，但是如果遇到手机短信、图形验证就会比较麻烦

**Comment by Bangood** [comment]
就是在登录的时候遇到了手机短信，我就想，能不能puppeteer重新打开chrominum的时候，就用我上次已经登录过的所有数据

**Comment by zhentaoo** [comment]
可以，你把上次的数据，保存到mongo等数据库中，每次重新打开的时候去服务端取

**Comment by Bangood** [comment]
大神，能不能加个QQ，请教点问题☺

**Comment by zhentaoo** [comment]
1904974327
