### ISSUE TITLE
hi why  Error: Failed to connect to chrome!

### ISSUE THREAD

**Issue by ZHENGGEGE** [zhentaoo/puppeteer-deep#5]
(node:25038) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to connect to chrome!
(node:25038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 

你好，请问按照readme的安装步骤运行以后发现是报这个错误  ，包括我自己写的例子也出现了这个  这是什么情况   
node  v8.2.1

**Comment by zhentaoo** [comment]
执行了哪条命令？npm test? 有没有把掘金的用户名／账号换成自己的？
如果打印PDF的话，不能使用headless: false模式
可以先试下最简单的demo,执行：npm run zhentaoo

**Comment by ZHENGGEGE** [comment]
发现问题了  原来是没有设置延迟，dom没加载好执行代码了

**Comment by zhentaoo** [comment]
ok
