### ISSUE TITLE
不行 Chromium revision is not downloaded

### ISSUE THREAD

**Issue by Yunnathai** [zhentaoo/puppeteer-deep#7]
一直下不了这个100M的Chromium revision

**Comment by zhentaoo** [comment]
网络不好？npm切到淘宝源试下，如果已经切了那就....

**Comment by xcuYao** [comment]
1. `npm install` 之后 检查下` node_modules/puppeteer/.local-chromium/` 目录或子目录下是否安装了chromium
2. 如果没有 建议修改源码 手动配置chromium的地址 比如:
```
...
(async() => {
    const browser = await puppeteer.launch({
        executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium',
        headless: false
    });
    ...
})();
```
3. chromium的[下载地址](https://download-chromium.appspot.com/)
