### ISSUE TITLE
Chromium revision is not downloaded

### ISSUE THREAD

**Issue by xuxiaoqiang33** [zhentaoo/puppeteer-deep#9]
运行时候一直报这个错误：
(node:10852) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: Chromium revision is not downloaded. Run npm install

(node:10852) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pr
ocess with a non-zero exit code.
应该是没有安装好Chromium，试了网上的很多方法都不行，？能告诉我怎么解决这个问题吗？

**Comment by xuxiaoqiang33** [comment]
搞定了，修改了一下npm的环境变量--> npm config -g set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

**Comment by RicoLiu** [comment]
我修改完环境变量之后还是报这个错
node --> 8.9.1
npm --> 5.6.0

**Comment by xuxiaoqiang33** [comment]
我的版本是这个
node --> v7.10.0
npm --> 4.2.0
